{{- if .Values.backend.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: todo-evolution-backend
  labels:
    {{- include "todo-evolution.labels" . | nindent 4 }}
    component: backend
automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
{{- end }}
