"""Add chat tables

Revision ID: fc63459e144e
Revises: 
Create Date: 2025-12-15 01:56:35.359763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import String

# revision identifiers, used by Alembic.
revision: str = 'fc63459e144e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_contexts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('context_type', String(length=50), nullable=False),
    sa.Column('context_key', String(length=100), nullable=False),
    sa.Column('context_value', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_operations_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('operation_type', String(length=50), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('operation_data', sa.JSON(), nullable=True),
    sa.Column('operation_result', sa.JSON(), nullable=True),
    sa.Column('status', String(length=20), nullable=False),
    sa.Column('error_message', String(length=1000), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('playing_with_neon')
    # Add missing task.completed_at column
    op.add_column('task', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('conversations', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('conversations', sa.Column('messages_count', sa.Integer(), nullable=False))
    op.add_column('conversations', sa.Column('last_message_at', sa.DateTime(), nullable=True))
    op.add_column('conversations', sa.Column('extra_data', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_conversation_created_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversation_updated_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversation_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.add_column('messages', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.add_column('messages', sa.Column('message_type', sa.Enum('TEXT', 'IMAGE', 'FILE', 'OPERATION_RESULT', name='messagetype'), nullable=False))
    op.add_column('messages', sa.Column('operation_status', sa.Enum('PENDING', 'PROCESSING', 'DELIVERED', 'FAILED', name='operationstatus'), nullable=False))
    op.add_column('messages', sa.Column('operation_type', String(length=50), nullable=True))
    op.add_column('messages', sa.Column('operation_result', sa.JSON(), nullable=True))
    op.add_column('messages', sa.Column('error_details', sa.JSON(), nullable=True))
    op.add_column('messages', sa.Column('extra_data', sa.JSON(), nullable=True))
    op.add_column('messages', sa.Column('processing_started_at', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('processing_completed_at', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_message_conversation_created'), table_name='messages')
    op.drop_index(op.f('ix_message_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_message_created_at'), table_name='messages')
    op.drop_index(op.f('ix_message_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_constraint(op.f('messages_user_id_fkey'), 'messages', type_='foreignkey')
    op.drop_column('messages', 'tool_calls')
    op.drop_column('messages', 'user_id')
    op.drop_column('messages', 'created_at')
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('messages', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('tool_calls', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('messages_user_id_fkey'), 'messages', 'user', ['user_id'], ['id'])
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_message_user_id'), 'messages', ['user_id'], unique=False)
    op.create_index(op.f('ix_message_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_message_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_message_conversation_created'), 'messages', ['conversation_id', 'created_at'], unique=False)
    op.drop_column('messages', 'retry_count')
    op.drop_column('messages', 'processing_completed_at')
    op.drop_column('messages', 'processing_started_at')
    op.drop_column('messages', 'extra_data')
    op.drop_column('messages', 'error_details')
    op.drop_column('messages', 'operation_result')
    op.drop_column('messages', 'operation_type')
    op.drop_column('messages', 'operation_status')
    op.drop_column('messages', 'message_type')
    op.drop_column('messages', 'timestamp')
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_conversation_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_conversation_updated_at'), 'conversations', ['updated_at'], unique=False)
    op.create_index(op.f('ix_conversation_created_at'), 'conversations', ['created_at'], unique=False)
    op.drop_column('conversations', 'extra_data')
    op.drop_column('conversations', 'last_message_at')
    op.drop_column('conversations', 'messages_count')
    op.drop_column('conversations', 'is_active')
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    op.drop_table('task_operations_log')
    op.drop_table('conversation_contexts')
    # ### end Alembic commands ###
