{{- if .Values.frontend.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: todo-evolution-frontend
  labels:
    {{- include "todo-evolution.labels" . | nindent 4 }}
    component: frontend
automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
{{- end }}
